language: en
namespaces: {
  dc:   'http://purl.org/dc/elements/1.1/',
  dct:  'http://purl.org/dc/terms/',
  doap: 'http://usefulinc.com/ns/doap#',
  foaf: 'http://xmlns.com/foaf/0.1/',
  s:    'http://schema.org/',
  v:    'http://rdf.data-vocabulary.org/#',
  xsd:  'http://www.w3.org/2001/XMLSchema#' }
title: Website Template
